[package]
name = "server-mappings"
version = "2.0.0+2025-08-07"
edition = "2021"
publish = false
license = "AGPL-3.0-only"

[build-dependencies]
phf_codegen = "0.11.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.105"
json5 = "0.4.1"

[dependencies]
phf = "0.11.1"
