[package]
name = "server-mappings"
version = "1.0.0+2024-01-21"
edition = "2021"

[build-dependencies]
phf_codegen = "0.11.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.105"
json5 = "0.4.1"

[dependencies]
phf = "0.11.1"
